name: Build Docker Image

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC authentication
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pwc:latest

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Keyless Sign Docker Image with Cosign
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign --yes ${{ secrets.DOCKER_USERNAME }}/pwc:latest
