name: Main Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - '/config/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - '/config/**'

jobs:
  sonarqube-SAST:
    uses: ./.github/workflows/sonarqube.yml
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  semgrep-SAST:
    needs: sonarqube-SAST
    uses: ./.github/workflows/semgrep.yml

  snyk-SCA:
    needs: semgrep-SAST
    uses: ./.github/workflows/snyk.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-image:
    needs: snyk-SCA
    uses: ./.github/workflows/build-docker-image
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
