name: OWASP ZAP DAST scan

on:
  workflow_call:
    secrets:
      DEFECTDOJO_API_TOKEN:
        required: true
      DEFECTDOJO_URL:
        required: true

jobs:
  owasp-zap:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://9.163.226.34'

      - name: Find zap_scan.zip
        run: find . -name "zap_scan.zip"

      - name: List all files recursively
        run: ls -lR
        
      - name: Upload ZAP Scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap_scan_json  # Artifact name (not a file)
          path: /

      - name: Download ZAP Scan results
        uses: actions/download-artifact@v4
        with:
          name: zap_scan_json

      - name: Import scan results into DefectDojo
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_TOKEN: ${{ secrets.DEFECTDOJO_API_TOKEN }}
          # Adjust the following values as needed:
          DEFECTDOJO_PRODUCT: 1
          DEFECTDOJO_ENGAGEMENT: 1
          DEFECTDOJO_SCAN_TYPE: "ZAP scan"
          DEFECTDOJO_ENVIRONMENT: "Production"
          SCAN_DATE: 2025-03-18
        run: |
          echo "Uploading zap scan to DefectDojo..."
          curl -k -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
            -F "file=@report_json.json" \
            -F "scan_type=$DEFECTDOJO_SCAN_TYPE" \
            -F "product=$DEFECTDOJO_PRODUCT" \
            -F "engagement=$DEFECTDOJO_ENGAGEMENT" \
            -F "environment=$DEFECTDOJO_ENVIRONMENT" \
            -F "scan_date=$SCAN_DATE" \
            -F "close_old_findings=true"
