name: OWASP ZAP DAST scan

on:
  workflow_call:
    secrets:
      DEFECTDOJO_API_TOKEN:
        required: true
      DEFECTDOJO_URL:
        required: true

jobs:
  owasp-zap:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://9.163.226.34'
          
      - name: Download ZAP Scan results
        uses: actions/download-artifact@v4
        with:
          name: zap_scan

      - name: Extract JSON report from ZIP
        run: |
          unzip zap_scan.zip
          ls -l  # List files to verify extraction

      - name: Import ZAP scan results into DefectDojo
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_TOKEN: ${{ secrets.DEFECTDOJO_API_TOKEN }}
          DEFECTDOJO_PRODUCT: 1
          DEFECTDOJO_ENGAGEMENT: 1
          DEFECTDOJO_SCAN_TYPE: "ZAP Scan"
          DEFECTDOJO_ENVIRONMENT: "Production"
          SCAN_DATE: 2025-03-18
        run: |
          JSON_FILE=$(ls *.json | head -n 1)  # Find the JSON file
          echo "Uploading $JSON_FILE to DefectDojo..."
          curl -k -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
            -F "file=@$JSON_FILE" \
            -F "scan_type=$DEFECTDOJO_SCAN_TYPE" \
            -F "product=$DEFECTDOJO_PRODUCT" \
            -F "engagement=$DEFECTDOJO_ENGAGEMENT" \
            -F "environment=$DEFECTDOJO_ENVIRONMENT" \
            -F "scan_date=$SCAN_DATE" \
            -F "close_old_findings=true"
