name: OWASP ZAP DAST scan

on:
  workflow_call:
    secrets:
      DEFECTDOJO_API_TOKEN:
        required: true
      DEFECTDOJO_URL:
        required: true
      ZAP_SCAN:
        required: true

jobs:
  owasp-zap:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ secrets.ZAP_TARGET }}
          cmd_options: '-x report_xml.xml'

      - name: Set current date for SCAN_DATE
        run: echo "SCAN_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Import scan results into DefectDojo
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_TOKEN: ${{ secrets.DEFECTDOJO_API_TOKEN }}
          DEFECTDOJO_PRODUCT: 1
          DEFECTDOJO_ENGAGEMENT: 3
          DEFECTDOJO_SCAN_TYPE: "ZAP Scan"
          DEFECTDOJO_ENVIRONMENT: "Production"
          SCAN_DATE: ${{ env.SCAN_DATE }}
        run: |
          echo "Uploading zap scan to DefectDojo..."
          curl -k -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
            -F "file=@report_xml.xml" \
            -F "scan_type=$DEFECTDOJO_SCAN_TYPE" \
            -F "product=$DEFECTDOJO_PRODUCT" \
            -F "engagement=$DEFECTDOJO_ENGAGEMENT" \
            -F "environment=$DEFECTDOJO_ENVIRONMENT" \
            -F "scan_date=$SCAN_DATE" \
            -F "close_old_findings=true"
