name: Trivy Image Scan

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DEFECTDOJO_API_TOKEN:
        required: true
      DEFECTDOJO_URL:
        required: true

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trivy set up
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: latest

      - name: Create directory for Trivy results
        run: mkdir -p trivy/results

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/pwc:latest
          severity: 'MEDIUM,HIGH,CRITICAL'
          format: 'json'
          output: 'trivy/results/trivy-report.json'
          exit-code: '0'
          vuln-type: 'os,library'
          ignore-unfixed: false

      - name: Upload Trivy JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy/results/

      - name: Download Trivy results artifact
        uses: actions/download-artifact@v4
        with:
          name: trivy-report

      - name: Set current date for SCAN_DATE
        run: echo "SCAN_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Import scan results into DefectDojo
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_TOKEN: ${{ secrets.DEFECTDOJO_API_TOKEN }}
          DEFECTDOJO_PRODUCT: 1
          DEFECTDOJO_ENGAGEMENT: 2
          DEFECTDOJO_SCAN_TYPE: "Trivy Scan"
          DEFECTDOJO_ENVIRONMENT: "Production"
          SCAN_DATE: ${{ env.SCAN_DATE }}
        run: |
          echo "Uploading trivy-report.json to DefectDojo..."
          curl -k -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
            -F "file=@trivy/results/trivy-report.json" \
            -F "scan_type=$DEFECTDOJO_SCAN_TYPE" \
            -F "product=$DEFECTDOJO_PRODUCT" \
            -F "engagement=$DEFECTDOJO_ENGAGEMENT" \
            -F "environment=$DEFECTDOJO_ENVIRONMENT" \
            -F "scan_date=$SCAN_DATE" \
            -F "close_old_findings=true"
