name: Trivy Image Scan

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trivy set up
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: latest

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/pwc:latest
          severity: 'MEDIUM,HIGH,CRITICAL'
          format: 'json'
          output: 'trivy-report.json'
          exit-code: '0'
          vuln-type: 'os,library'
          ignore-unfixed: false
