name: Semgrep Analysis

on:
  workflow_call:
    secrets:
      DEFECTDOJO_API_TOKEN:
        required: true
      DEFECTDOJO_URL:
        required: true

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan
        run: |
          mkdir -p semgrep/results
          semgrep --config p/default --json --output=semgrep/results/semgrep.json

      - name: Upload Semgrep results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep/results/

      - name: Download Semgrep results artifact
        uses: actions/download-artifact@v4
        with:
          name: semgrep-results

      - name: Set current date for SCAN_DATE
        run: echo "SCAN_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Import scan results into DefectDojo
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_TOKEN: ${{ secrets.DEFECTDOJO_API_TOKEN }}
          DEFECTDOJO_PRODUCT: 1
          DEFECTDOJO_ENGAGEMENT: 1
          DEFECTDOJO_SCAN_TYPE: "Semgrep JSON Report"
          DEFECTDOJO_ENVIRONMENT: "Production"
          SCAN_DATE: ${{ env.SCAN_DATE }}
        run: |
          echo "Uploading semgrep/results/semgrep.json to DefectDojo..."
          curl -k -X POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            -H "Authorization: Token $DEFECTDOJO_API_TOKEN" \
            -F "file=@semgrep/results/semgrep.json" \
            -F "scan_type=$DEFECTDOJO_SCAN_TYPE" \
            -F "product=$DEFECTDOJO_PRODUCT" \
            -F "engagement=$DEFECTDOJO_ENGAGEMENT" \
            -F "environment=$DEFECTDOJO_ENVIRONMENT" \
            -F "scan_date=$SCAN_DATE" \
            -F "close_old_findings=true"
