name: Semgrep Analysis

on:
  workflow_call:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan
        run: |
          mkdir -p semgrep/results
          semgrep --config auto --error --json --output=semgrep/results/semgrep.json
      - name: upload semgrep results
        id: upload-semgrep-results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-results
          path: semgrep/results/

  import-semgrep-report:
    name: import semgrep report
    runs-on: ubuntu-latest
    steps:
      - name: download scan results artifact
        id: download-scan-results-artifact
        uses: actions/download-artifact@v3
        with:
          name: semgrep-results
      - name: import scan results into defectdojo
        id: import-scan-results-into-defectdojo
        uses: portswigger-cloud/defectdojo-github-action@v1
        with:
          defectdojo-url: https://40.68.56.81:8443
          defectdojo-username: ${{ secrets.defectdojo-username }}
          defectdojo-password: ${{ secrets.defectdojo-password }}
          scan-results-file-name: semgrep.json
