name: Python SCA scan
on:
  workflow_run:
    workflows: ["Semgrep Analysis"]
    types:
      - completed
      
jobs:
  security:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - run: echo 'The triggering workflow failed'
      - name: Fail Job
        run: exit 1
