name: Python SCA scan

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Run Snyk and output the report in JSON format
      - name: Run Snyk SCA scan and output JSON
        run: snyk test --json > snyk-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      

      # Upload the JSON report as an artifact
      - name: Upload Snyk JSON report artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-json-report
          path: snyk-report.json
