name: Python SCA scan

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true
      
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Run Snyk Test and Generate JSON Report
        run: snyk test --json > snyk_report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
