name: SonarQube Analysis

on:
  workflow_call:
    inputs:
      SONAR_HOST_URL:
        required: true
        type: string
      SONAR_TOKEN:
        required: true
        type: string


jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify Java Version
        run: java -version

      - name: Cache SonarQube packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Echo Environment Variables
        run: |
          echo "SONAR_HOST_URL=${{ inputs.SONAR_HOST_URL }}"
          echo "SONAR_TOKEN=${{ inputs.SONAR_TOKEN }}"

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.0.0
        env:
          SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ inputs.SONAR_HOST_URL }}
        with:
          projectBaseDir: ./
          args: -X -Dproject.settings=config/sonar-project.properties
